title: LotteryNumber
destination: docs
google_analytics: UA-145243696-2
sass:
  sass_dir: css
  style:    compressed
url: "https://lotterynumber.net" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap